spring:
  mail:
    properties:
      mail:
        smtp:
          starttls:
            enable: 'true'
          auth: 'true'
    host: smtp.gmail.com
    username: 8.aver5eng@gmail.com
    password: dxzctziaxgijcvtn
    port: 587

  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql:containers-us-west-57.railway.app:6677/railway
    username: root
    password: ucVLE1foUopXyNpN7kQw
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
server:
  error:
    include-message: always

